### ISSUE TITLE
Unity Geometry Materials Not Working - No Effect On Sound

### ISSUE THREAD

**Issue by CraigApps** [ValveSoftware/steam-audio#117] opened 2020-04-28 10:39 UTC
Hello

I'm very new to the world of Unity so there is a strong possibility I'm missing something glaringly obvious, but here goes!

Firstly, if this makes a difference, I am using Mac OS.

I'm trying to create and immersive sound experience, in which a user can move the player around and hear full 3D sound, complete with HRTF and have the materials of the room effect the audio sources eg echoes, occlusion etc. However, although I am getting a 3D sound as far as directivity is concerned, the geometry of the environment has no effect on my audio sources.

Following the documentation supplied by Steam Audio, I have created my project, imported the Steam Audio Package and selected Steam Audio for my Spatializer Plugin and Ambisonic Plugin.

After selecting Steam Audio from the Window tab, I have created my walls and floor using cubes, stored them in an empty object, and tagged the empty object with a Steam Audio Geometry component and selected Export All Children. Then, I have added Steam Audio Material component and selected Concrete (I thought this would give an obvious echo to test). The documentation then suggest Pre-Export Scene in Window>Steam Audio 'to ensure scene setup changes are available to Steam Audio'. I don't fully understand the importance of this so there might be something here where I am going wrong.

Once I have quickly create a player using a capsule and camera, I add a Steam Audio Listener to the camera, and create a Cube to attach my Audio Source to. I check 'Play On Awake' and 'Loop', 'Spatial Blend' is set to '3D' and check 'Spatialize'. After adding a Steam Audio Source to my cube, the setup in this component is;
Direct Binaural - checked;
HRTF Interpolation - Bilinear;
Direct Sound Occlusion - On, Frequency Dependant Transmission;
Occlusion Method -Raycast;
Physics Based Attenuation - checked;
Air Absorption - checked;

I also have Indirect sound; Reflections checked, simulation type at Realtime and Indirect Binaural checked.

Now, I don't believe there is anything I have missed but the materials in the space seem to have no effect on the sound.

Sorry if there is a lot to read through, but I didn't know a better way to describe it. I'm pulling my hair out as I can't see why this isn't working and I'm hoping it's a really silly mistake!

Any ideas?

Thanks in Advance

**Comment by achandak** [comment] 2020-04-28 16:07
@CraigApps - Make sure to pre-export scene, there should be errors in the console if scene is missing. So, this should be easy to spot. 

Also, make sure there is no geometry around the source itself, i.e. your make sure cube that is part of your Audio Source is not marked as Steam Audio Geometry.

If you would like us to look further, feel free to share a reproducible project with us.

**Comment by CraigApps** [comment] 2020-04-28 17:04
Hi @achandak - Thank you for getting back to me.

I Pre-Exported the scene before creating my capsule player/camera as the documentation suggested. If I'm honest, with my very limited Unity knowledge, this step confuses me a little bit. Could you explain the purpose of this for me so I can understand better please?

When I pre-exported through the Steam Audio window, it said it went to a folder but wasn't there. This appeared later but appeared as un inoperable file. I have also simply saved the scene in my assets.

I've attached a picture of alerts I'm getting in the bottom right hand corner, but there is no Window > Phono > Simulation

![Screen Shot 2020-04-28 at 18 01 04](https://user-images.githubusercontent.com/62509758/80515878-8f374180-897a-11ea-9fa3-59d1c209a3c5.png)


I've double checked and there is no geometry tagged on my cube audio source.

When I tick all of the selections above, specifically 'Reflections', it's making the audio source sound strange.

How would I share a reproducible project? I've tried to .zip the file but it says it's too big. Sorry, I'm new to this.

Many thanks

**Comment by achandak** [comment] 2020-04-28 17:13
@CraigApps - Scene export generates a .phononscene file in StreamingAssets/ folder so your game has access to geometry at runtime. When you hit Play in Editor, do you get any error messages?

May be you can zip only relevant files. Skip including Steam Audio related files, we can just use the latest release on our end. Include minimum set of files that help us reproduce the issue.

**Comment by CraigApps** [comment] 2020-04-29 09:57
@achandak - thank you, that makes a bit more sense now. I don't appear to be getting any error messages, other than the messages I showed in my last screenshot.

I'm not fully confident on what is and isn't relevant, so I have zipped the folder and you can find it here via WeTransfer:

https://we.tl/t-dtmv9CtTEr

Let me know if this doesn't work and I'll try again.

Thank you for your help with this.

**Comment by achandak** [comment] 2020-04-29 15:45
@CraigApps - Below are a few suggestions for the project you sent.

- Consider updating to latest version of Steam Audio. You are using Beta.17, we recently updated to Beta.18.
- Change Simulation Settings from Low to Custom and update number of bounces. See [documentation](https://valvesoftware.github.io/steam-audio/doc/phonon_unity.html#simulation-settings) for more detail.
- I also noticed that Floor was not marked as Steam Audio Geometry, not sure if that was intentional.

Let us know if that help solve the problem.

**Comment by CraigApps** [comment] 2020-04-30 10:19
@achandak I've gone into the simulation settings as suggested and increased the bounces in the Realtime settings...and this seems to have made a difference! There now appears to be echoes from the environment. However, when changing the material from concrete to carpet (i thought this would be the most recognisable change) it doesn't make the sound any different.

Do I need to pre-export the scene after making changes to the environment? just to clarify, I have done this, but it hasn't seemed to changed anything.

Regarding the newer version on steam audio, I have dowloaded Beta.18. What is the correct way to replace 17 within my project?

I had not tagged the floor in this project, but I had in previous tests and there seemed no difference to my problem at the time. I have tagged it now though as this will, as you suggest, probably help.

Sorry again for all the question, I am very much learning this all as I go along.

Thank you for your continued help.

**Comment by achandak** [comment] 2020-04-30 15:15
Where do you change the material? Feel free to go through [this section](https://valvesoftware.github.io/steam-audio/doc/phonon_unity.html#specifying-acoustic-materials) of the documentation and let me know if it helps.

[Here](https://steamcommunity.com/app/596420/discussions/0/2264691117412106793/) are the notes to transition from Beta.17 to Beta.18 in your project.

**Comment by CraigApps** [comment] 2020-04-30 16:27
I change the material in the 'Walls' root object of my 4 walls, with export all children checked. I believe you can preset the material in the Steam Audio Manager Settings but this should be overridden by the geometry on the objects. 

Everything I've done thus far has been following the documentation, which is why it's caused me such a headache as I feel I've been missing something obvious! Changing the simulation settings to custom helped, however I have now set it to high without having to customise and this also seems to be effective. It now simply appears to be that my materials are not changing, and it's set to the same reverb effect etc.

I will follow the notes to upgrade steam as well.

It seems I must pre-export scene after any changes to the environment, is this correct?

**Comment by achandak** [comment] 2020-04-30 17:57
Yes, any changes to the environment requires a scene pre-export. 

Audio clip in your project is using a low frequency audio source. If you select Carpet and then switch to Custom, you can see the absorption properties of Carpet. It still has relatively small low frequency absorption. Feel free to adjust it to better suit your needs. I am able to hear material changes this way on the sample project you shared.

I am closing this issue, feel free to reopen it if the issue is not resolved with the latest plugin and suggestions above. Feel free to upload another project if you are seeing any further issues.

**Closed by achandak** 2020-04-30 17:57 UTC

**Comment by CraigApps** [comment] 2020-05-04 07:51
@achandak Thank you for all of your help.
