### ISSUE TITLE
[4.0.0] Unity crashing when realtime reflection is enabled

### ISSUE THREAD

**Issue by virtuapng** [ValveSoftware/steam-audio#166] opened 2021-09-12 06:06 UTC
Unity crashes when realtime reflection is enabled.

1. I'm using Unity 2020.3.14f1 with the steam ray tracer settings scene type set to unity. 
2. Baked reflections appear to work but real-time always crashes.
3. There is a single audio geometry object between the sound and the listener

If you need any more info feel free to ask.

**Comment by lakulish** [comment] 2021-09-15 22:35
Duplicate of #158

**Closed** 2021-09-15 22:35 UTC
