### ISSUE TITLE
Unity integration - PlayOneShot

### ISSUE THREAD

**Issue by pragmascript** [ValveSoftware/steam-audio#31] opened 2017-06-19 15:33 UTC
There is  a problem with the Unity integration that when you use `AudioSource.PlayOneShot()` (https://docs.unity3d.com/ScriptReference/AudioSource.PlayOneShot.html) the PhononAudioSource doesn't seem to have any effect.

Since using `PlayOneShot()` is probably the most common way to play sounds in Unity this seems to be a rather important issue.
(Using Beta5 version)

**Comment by achandak** [comment] 2017-06-20 00:44
@pragmascript - We looked into this issue and think there is some issue on Unity's side. Basically, custom effects created with OnAudioReadFilter and called with PlayOneShot has different behavior depending on whether Play On Awake is checked or not on an Audio Source.

Can you try the following and see if the issue is resolved?
- Make sure that Play On Awake is not checked on the Audio Source you are calling PlayOneShot on.
- Trigger PlayOneShot and check if Steam Audio effect are applied correctly.

**Comment by pragmascript** [comment] 2017-06-20 17:00
@achandak I can confirm that when PlayOnAwake is unchecked it works as expected.
Thanks for the quick response

**Comment by achandak** [comment] 2017-06-20 17:06
@pragmascript - Thanks for follow up. We will continue to look into what is happening when PlayOnAwake is checked. We have reported a bug with Unity for the time being.

**Comment by achandak** [comment] 2017-07-22 00:52
@pragmascript - We received following feedback from Unity on the issue. According to them this behavior is by design. I am copy pasting their response below and closing this particular issue.

> It is by design because when there is an AudioSource that has no clip assigned but does have a MonoBehaviour implementing OnAudioFilterRead, it will instantiate the OnAudioFilterRead as a source when the sound is started either via the "Play On Awake" flag or a regular Play() call. When “Play On Awake” is off and Play() is not called, the PlayOneShot call will instantiate the OnAudioFilterRead as an effect that filters the signal mix of the one-shot sources.

**Closed** 2017-07-22 00:52 UTC
