### ISSUE TITLE
iplRotateAmbisonicsAudioBuffer no effect on audio data.

### ISSUE THREAD

**Issue by mecowhy** [ValveSoftware/steam-audio#38] opened 2017-07-12 10:45 UTC
Hi,

I'm developing gstreamer plugin based on phonon C API, I created 1st order test file that I'm able to play using iplApplyAmbisonicsBinauralEffect and it gets rendered properly, but if I try to rotate the the ambisonics data using: iplRotateAmbisonicsAudioBuffer  before i apply the effect nothing happens to the data in the output buffer (tried both in place rotation and separate in and out buffers, rotator is initialized and rotation set). What I do looks more or less like:

//once at beginning:
iplCreateBinauralRenderer
iplCreateAmbisonicsBinauralEffect
iplCreateAmbisonicsRotator

//each time the viewer moves/rotates
iplSetAmbisonicsRotation    // the quat is normalized.

//on each audio frame:
iplRotateAmbisonicsAudioBuffer
iplApplyAmbisonicsBinauralEffect

I tried rotation in each axis but it looks like the data remains untouched.

many thanks in advance 

mecowhy

**Comment by lakulish** [comment] 2017-07-12 17:18
@mecowhy The overall sequence of calls looks fine, but more details would help. Can you provide more of the actual code where you're using the Steam Audio API to do Ambisonics rotation? Thanks.

**Comment by mecowhy** [comment] 2017-07-13 07:36
@lakulish thanks for quick response,

I'll prepare some extract from my code that compiles and demonstrates the issue.

**Comment by mecowhy** [comment] 2017-07-14 15:07
`
#include <algorithm>
#include <fstream>
#include <iterator>
#include <vector>
#include <random>
#include <phonon.h>
#include <cstdlib>
#include <ctime>

#define AMBISONICS_ORDER 1
#define TestChannels 4	//1 order ambisonics
#define TestSamples 100
#define TestDataSize  TestSamples*TestChannels*4
#define M_PI 3.14f
#define RAD(x) x*M_PI/180.f

//https://en.wikipedia.org/wiki/Conversion_between_quaternions_and_Euler_angles#Source_Code
IPLQuaternion toQuaternion(double pitch, double roll, double yaw)
{
	IPLQuaternion q;
	double t0 = cos(yaw * 0.5);
	double t1 = sin(yaw * 0.5);
	double t2 = cos(roll * 0.5);
	double t3 = sin(roll * 0.5);
	double t4 = cos(pitch * 0.5);
	double t5 = sin(pitch * 0.5);

	q.w = t0 * t2 * t4 + t1 * t3 * t5;
	q.x = t0 * t3 * t4 - t1 * t2 * t5;
	q.y = t0 * t2 * t5 + t1 * t3 * t4;
	q.z = t1 * t2 * t4 - t0 * t3 * t5;
	return q;
}

double normQuaternion(IPLQuaternion q)
{
	return sqrt(q.w*q.w + q.x*q.x + q.y*q.y + q.z*q.z);
}

IPLQuaternion normalizeQuaternion(IPLQuaternion q)
{
	double norm = normQuaternion(q);
	IPLQuaternion result;
	result.w = q.w / norm;
	result.x = q.x / norm;
	result.y = q.y / norm;
	result.z = q.z / norm;
	return result;
}

IPLQuaternion toQuaternionFromDeg(double pitch, double roll, double yaw)
{
	return normalizeQuaternion(toQuaternion(RAD(pitch), RAD(roll), RAD(yaw)));
}

int main(int argc, char** argv)
{
	//setup input format.
	IPLAudioFormat ambisonics;
	ambisonics.channelLayoutType = IPL_CHANNELLAYOUTTYPE_AMBISONICS;
	ambisonics.channelOrder = IPL_CHANNELORDER_INTERLEAVED;
	ambisonics.numSpeakers = 4;
	ambisonics.ambisonicsOrder = AMBISONICS_ORDER;
	ambisonics.ambisonicsOrdering = IPL_AMBISONICSORDERING_ACN;
	ambisonics.ambisonicsNormalization = IPL_AMBISONICSNORMALIZATION_SN3D;

	IPLhandle rotator{ nullptr };
	IPLerror rotatorError = iplCreateAmbisonicsRotator(AMBISONICS_ORDER, &rotator);

	IPLAudioBuffer inBuffer, outBuffer;
	
	//prepare input buffer
	inBuffer.format = ambisonics;
	inBuffer.numSamples = TestSamples;
	inBuffer.interleavedBuffer = (IPLfloat32*)malloc(TestDataSize);

	//generate some random data
	srand(static_cast <unsigned> (time(0)));
	for (auto i = 0; i < TestSamples; i++)
	{
		inBuffer.interleavedBuffer[i] = static_cast <float> (rand()) / static_cast <float> (RAND_MAX);
	}

	//prepare output buffer
	outBuffer.format = ambisonics;
	outBuffer.numSamples = TestSamples;
	outBuffer.interleavedBuffer = (IPLfloat32*)malloc(TestDataSize);
	memset(outBuffer.interleavedBuffer, 0, TestDataSize);

	//compute some rotation quat
	IPLQuaternion rotation = toQuaternionFromDeg(90.0f,90.0f,90.0f);

	//set rotation to rotator.
	iplSetAmbisonicsRotation(rotator, rotation);

	//apply rotation to input buffer 
	iplRotateAmbisonicsAudioBuffer(rotator, inBuffer, outBuffer);

	//check the result.
	for (auto i = 0; i < TestSamples; i++)
	{
		if(inBuffer.interleavedBuffer[i]!= outBuffer.interleavedBuffer[i] && outBuffer.interleavedBuffer[i]!=0)
			printf("RotationWorks! \n");
	}
	
	//cleanup
	free(inBuffer.interleavedBuffer);
	free(outBuffer.interleavedBuffer);
	iplDestroyAmbisonicsRotator(&rotator);
	return 0;
}
`

ok there it is, no change in output buffer.
the example is minimal but from what I understand it should be enough, the rotation of ambisnonics data doesn't depend on renderer, output (from renderer) format etc, what should really matter is:
- ambisonics order  (channelNumber)
- channel ordering 
- buffer length
- angle (quat) of rotation.


many thanks in advance




[PhononRotatorTest.zip](https://github.com/ValveSoftware/steam-audio/files/1148786/PhononRotatorTest.zip)

**Comment by lakulish** [comment] 2017-07-14 16:43
@mecowhy Thanks, this helps. Can you try changing the Ambisonics normalization to `IPL_AMBISONICSNORMALIZATION_N3D` and testing whether that causes the output buffer to change?

**Comment by mecowhy** [comment] 2017-07-17 08:28
@lakulish nope, no still no change.
I updated a demo code a bit:
```
#include <algorithm>
#include <fstream>
#include <iterator>
#include <vector>
#include <random>
#include <phonon.h>
#include <cstdlib>
#include <ctime>

#define AMBISONICS_ORDER 1
#define TestChannels 4	//1 order ambisonics
#define TestSamples 100
#define TestDataSize  TestSamples*TestChannels*4
#define M_PI 3.14f
#define RAD(x) x*M_PI/180.f

//https://en.wikipedia.org/wiki/Conversion_between_quaternions_and_Euler_angles#Source_Code
IPLQuaternion toQuaternion(double pitch, double roll, double yaw)
{
	IPLQuaternion q;
	double t0 = cos(yaw * 0.5);
	double t1 = sin(yaw * 0.5);
	double t2 = cos(roll * 0.5);
	double t3 = sin(roll * 0.5);
	double t4 = cos(pitch * 0.5);
	double t5 = sin(pitch * 0.5);

	q.w = t0 * t2 * t4 + t1 * t3 * t5;
	q.x = t0 * t3 * t4 - t1 * t2 * t5;
	q.y = t0 * t2 * t5 + t1 * t3 * t4;
	q.z = t1 * t2 * t4 - t0 * t3 * t5;
	return q;
}

double normQuaternion(IPLQuaternion q)
{
	return sqrt(q.w*q.w + q.x*q.x + q.y*q.y + q.z*q.z);
}

IPLQuaternion normalizeQuaternion(IPLQuaternion q)
{
	double norm = normQuaternion(q);
	IPLQuaternion result;
	result.w = q.w / norm;
	result.x = q.x / norm;
	result.y = q.y / norm;
	result.z = q.z / norm;
	return result;
}

IPLQuaternion toQuaternionFromDeg(double pitch, double roll, double yaw)
{
	return normalizeQuaternion(toQuaternion(RAD(pitch), RAD(roll), RAD(yaw)));
}

int main(int argc, char** argv)
{
	//setup input format.
	IPLAudioFormat ambisonics;
	ambisonics.channelLayoutType = IPL_CHANNELLAYOUTTYPE_AMBISONICS;
	ambisonics.channelOrder = IPL_CHANNELORDER_INTERLEAVED;
	ambisonics.numSpeakers = 4;
	ambisonics.ambisonicsOrder = AMBISONICS_ORDER;
	ambisonics.ambisonicsOrdering = IPL_AMBISONICSORDERING_ACN;
	ambisonics.ambisonicsNormalization = IPL_AMBISONICSNORMALIZATION_SN3D;

	//create rotator
	IPLhandle rotator{ nullptr };
	IPLerror rotatorError = iplCreateAmbisonicsRotator(AMBISONICS_ORDER, &rotator);

	//allocate memory for input and output buffers.
	IPLfloat32* inData = (IPLfloat32*)malloc(TestDataSize);
	IPLfloat32* outData = (IPLfloat32*)malloc(TestDataSize);
	memset(outData, 0, TestDataSize);

	//generate some random data
	srand(static_cast <unsigned> (time(0)));
	for (auto i = 0; i < TestDataSize/4; i++)
	{
		inData[i] = static_cast <float> (rand()) / static_cast <float> (RAND_MAX);
	}

	IPLAudioBuffer inBuffer, outBuffer;

	//prepare input buffer
	inBuffer.format = ambisonics;
	inBuffer.numSamples = TestSamples;
	inBuffer.interleavedBuffer = inData;
	inBuffer.deinterleavedBuffer = &inData;

	//prepare output buffer
	outBuffer.format = ambisonics;
	outBuffer.numSamples = TestSamples;
	outBuffer.interleavedBuffer = outData;
	outBuffer.deinterleavedBuffer = &outData;

	//compute some rotation quat
	IPLQuaternion rotationQuat = toQuaternionFromDeg(90.0f,90.0f,90.0f);

	//set rotation to rotator.
	iplSetAmbisonicsRotation(rotator, rotationQuat);

	//apply rotation to input buffer 
	iplRotateAmbisonicsAudioBuffer(rotator, inBuffer, outBuffer);

	//check the result.
	for (auto i = 0; i < TestSamples; i++)
	{
		if(inData[i]!= outData[i] && outData[i]!=0)
			printf("RotationWorks! \n");
	}
	
	//cleanup
	free(inData);
	free(outData);
	iplDestroyAmbisonicsRotator(&rotator);
	return 0;
}

```

**Comment by grrrwaaa** [comment] 2017-07-18 01:46
I'm also seeing null/odd behaviour with iplRotateAmbisonicsAudioBuffer. With the code below, the rotation effect has no effect whatsoever on the output buffer, regardless what the quaternion is set to. 

However I also noticed in the comments for `iplRotateAmbisonicsAudioBuffer()` it states that the input and output buffers can be the same, so I tried that too (`#define RE_USE_INPUT_BUFFER`). In that case, what I get is silence, unless my framesize is 64 samples, in which case I get a horribly loud pulse wave. 

```
double samplerate = 44100;
int framesize = 512;

IPLContext context;
IPLRenderingSettings settings;
IPLHrtfParams hrtf_params;
IPLAudioFormat input_format; 
IPLAudioFormat hrtf_format;
	
IPLhandle binaural_renderer = 0;
IPLhandle ambisonic_hrtf_effect = 0;
IPLhandle ambisonic_rotator = 0;
	
IPLfloat32 * source_buffer;
IPLfloat32 * rotated_buffer;
IPLfloat32 * output_buffer;

float quat[4];
			
void setup() {
	settings.convolutionType = IPL_CONVOLUTIONTYPE_PHONON;
	settings.frameSize = framesize;
	settings.samplingRate = samplerate;
	
	hrtf_params.type = IPL_HRTFDATABASETYPE_DEFAULT; // or CUSTIOM
	hrtf_params.hrtfData = 0;	// Must be NULL.

	// binaural
	if (IPL_STATUS_SUCCESS != iplCreateBinauralRenderer(context, settings, hrtf_params, &binaural_renderer)) {
		error(0, "failed to create binaural renderer");
		return;
	}
	
	input_format.ambisonicsOrder = 1;
	input_format.numSpeakers = 4; 
	input_format.channelLayoutType = IPL_CHANNELLAYOUTTYPE_AMBISONICS;
	input_format.channelOrder = IPL_CHANNELORDER_INTERLEAVED;
	input_format.ambisonicsOrdering = IPL_AMBISONICSORDERING_FURSEMALHAM; 	
	input_format.ambisonicsNormalization = IPL_AMBISONICSNORMALIZATION_N3D; 
	
	hrtf_format.channelLayoutType	= IPL_CHANNELLAYOUTTYPE_SPEAKERS;
	hrtf_format.channelLayout		= IPL_CHANNELLAYOUT_STEREO;
	hrtf_format.numSpeakers			= 2;
	hrtf_format.channelOrder		= IPL_CHANNELORDER_INTERLEAVED;
	
	if (IPL_STATUS_SUCCESS != iplCreateAmbisonicsBinauralEffect(binaural_renderer,
																input_format,
																hrtf_format,
																&ambisonic_hrtf_effect)) {
		error(0, "failed to create Ambisonics HRTF effect");
		return;
	}
	
	if (IPL_STATUS_SUCCESS != iplCreateAmbisonicsRotator(input_format.ambisonicsOrder, &ambisonic_rotator)) {
		error(0, "failed to create Ambisonics rotator effect");
		return;
	}
	
	// allocate buffers
	source_buffer = new float[4096 * 4];
	rotated_buffer = new float[4096 * 4];
	output_buffer = new float[4096 * 2];
	
	// a 90' rotation around X:	
	quat[0] = quat[3] = 0.707;
	quat[1] = quat[2] = 0.;
}


void perform64(double **ins, long numins, double **outs, long numouts, long sampleframes) {
	
	IPLAudioBuffer inbuffer;
	inbuffer.format = input_format;
	inbuffer.numSamples = sampleframes;
	inbuffer.interleavedBuffer = source_buffer;
	
	IPLAudioBuffer rotbuffer;
	rotbuffer.format = input_format;
	rotbuffer.numSamples = sampleframes;
	rotbuffer.interleavedBuffer = rotated_buffer;
	
	IPLAudioBuffer outbuffer;
	outbuffer.format = hrtf_format;
	outbuffer.numSamples = sampleframes;
	outbuffer.interleavedBuffer = output_buffer;
	
	// copy input:
	{
		t_double * src0 = ins[0];
		t_double * src1 = ins[1];
		t_double * src2 = ins[2];
		t_double * src3 = ins[3];
		IPLfloat32 * dst = source_buffer;
		int n = sampleframes;
		while (n--) {
			*dst++ = *src0++;
			*dst++ = *src1++;
			*dst++ = *src2++;
			*dst++ = *src3++;
		}
	}
	
	IPLQuaternion q; // xyzw format
	q.x = quat[0];
	q.y = quat[1];
	q.z = quat[2];
	q.w = quat[3];
	iplSetAmbisonicsRotation(ambisonic_rotator, q);

#ifdef RE_USE_INPUT_BUFFER
	iplRotateAmbisonicsAudioBuffer(ambisonic_rotator, inbuffer, inbuffer);
	iplApplyAmbisonicsBinauralEffect(ambisonic_hrtf_effect, inbuffer, outbuffer);
#else		
	iplRotateAmbisonicsAudioBuffer(ambisonic_rotator, inbuffer, rotbuffer);
	iplApplyAmbisonicsBinauralEffect(ambisonic_hrtf_effect, rotbuffer, outbuffer);
#endif		
	// copy output:
	{
		IPLfloat32 * src = output_buffer;
		t_double * dst0 = outs[0];
		t_double * dst1 = outs[1];
		int n = sampleframes;
		while (n--) {
			*dst0++ = *src++;
			*dst1++ = *src++;
		}
	}
}
```

**Comment by lakulish** [comment] 2017-07-18 17:56
@mecowhy Ah, I didn't notice this the last time around, but it looks like you're using `IPL_CHANNELORDER_INTERLEAVED`. Can you switch to `IPL_CHANNELORDER_DEINTERLEAVED` and try again?

@grrrwaaa There seem to be two separate issues here. For the rotation, try using `IPL_CHANNELORDER_DEINTERLEAVED`, `IPL_AMBISONICSORDERING_ACN`, and `IPL_AMBISONICSNORMALIZATION_N3D` for your input buffer. For the loud noise at 64 samples, that seems to be an issue with the Ambisonics binaural effect, which we are now working on reproducing.

We will update the documentation for Ambisonics rotation to better indicate what Ambisonics settings are supported.

**Comment by MarcelInTO** [comment] 2017-10-03 16:02
Is there any definitive documentation on what combinations of channelOrder, ambisonicOrdering, and ambisonicNormalization are supported in order for iplRotateAmbisonicsAudioBuffer() to work? 

Is there any other combination besides  IPL_CHANNELORDER_DEINTERLEAVED, IPL_AMBISONICSORDERING_ACN, and IPL_AMBISONICSNORMALIZATION_N3D  that works for the input buffer?

**Comment by lakulish** [comment] 2017-10-10 21:48
@MarcelInTO At the moment, the only supported combination is `IPL_CHANNELORDER_DEINTERLEAVED`, `IPL_AMBISONICSORDERING_ACN`, and `IPL_AMBISONICSNORMALIZATION_N3D` for the input buffer. You can use `iplConvertAudioBufferFormat` to convert between different Ambisonics orderings and normalizations, and `iplDeinterleaveAudioBuffer` to convert from interleaved to deinterleaved.

**Comment by mecowhy** [comment] 2017-10-19 10:02
@lakulish so iplRotateAmbisonicsAudioBuffer  works (input and output) only on IPL_CHANNELORDER_DEINTERLEAVED format right ? so assuming I have IPL_CHANNELORDER_INTERLEAVED on both ends I have to:
- iplConvertAudioBufferFormat  IPL_CHANNELORDER_INTERLEAVED -> IPL_CHANNELORDER_DEINTERLEAVED
- iplRotateAmbisonicsAudioBuffer (IPL_CHANNELORDER_DEINTERLEAVED)
- iplConvertAudioBufferFormat IPL_CHANNELORDER_DEINTERLEAVED ->  IPL_CHANNELORDER_INTERLEAVED 

or can I omit last step and just pass  IPL_CHANNELORDER_INTERLEAVED  as outputbuffer to iplRotateAmbisonicsAudioBuffer  ?

**Comment by mecowhy** [comment] 2017-10-19 14:55
ok it looks like iplConvertAudioBufferFormat doesn't convert between intreleaved and deintreleaved iplDeinterleaveAudioBuffer but  iplDeinterleaveAudioBuffer/iplInterleaveAudioBuffer does. anyway now I get some weird noise and distortions after passing my samples through iplRotateAmbisonicsAudioBuffer.

**Comment by MarcelInTO** [comment] 2017-10-19 15:54
I am curious what platform you are running on.  We have been using
iplRotateAmbisonicAudioBuffer without a problem on the PC. Works well. On
Android however, with the same data the resulting spatialization is clearly
not correct. We are still investigating whether we believe it is an issue
with iplRotateAmbisonicAudioBuffer  or something step in our pipeline.


M.

**Comment by mecowhy** [comment] 2017-10-19 16:01
the noises I mentioned I observed on Windows, on Android didn't tested yet. You can try implement rotations by yourself ,it isn't too difficult , just keep #50 in mind.

**Comment by lakulish** [comment] 2017-10-19 17:41
@mecowhy The following sequence should work:

* `iplDeinterleaveAudioBuffer` to deinterleave the input
* `iplConvertAudioBufferFormat` to convert the deinterleaved buffer to ACN/N3D
* `iplRotateAmbisonicsBuffer` to rotate the deinterleaved ACN/N3D buffer
* `iplConvertAudioBufferFormat` to convert the rotated buffer to the format you need
* `iplInterleaveAudioBuffer` to interleave the format-converted, rotated buffer

Let us know if this sequence does not work for you.

**Comment by mecowhy** [comment] 2017-10-20 13:07
@lakulish it looks like it rotates the soundfield but it introduces some distortion on some angles. and it seems that it comes from the rotator, because it occurs if I'm changing yaw value on Front/Back and Left/Right Test files and not Up/Down where the rotator has not much to do. Anyway it would be cool if the phonon functions could return some error code, processed samples...

**Comment by bjornbytes** [comment] 2021-02-23 03:51
I just ran into this as well.  I was using 1st order interleaved Furse-Malham ambisonic samples and was confused why the rotator didn't seem to do anything.  I can confirm that the "deinterleave, convert, rotate, convert, interleave" sequence works, although it's cumbersome.

**Comment by lakulish** [comment] 2021-07-29 17:55
Can you check if this issue still occurs with the latest release: https://github.com/ValveSoftware/steam-audio/releases/tag/v4.0.0.

**Comment by kisak-valve** [comment] 2021-09-03 18:24
Closing pending feedback.

**Closed by kisak-valve** 2021-09-03 18:24 UTC
Labels: Need Retest
