### ISSUE TITLE
`iplBinauralEffectApply` always outputs silence on armv8

### ISSUE THREAD

**Issue by cshenton** [ValveSoftware/steam-audio#331] opened 2024-03-17 01:51 UTC
**System Information**
Please provide the following information about your system:
- Steam Audio version: 4.5.2
- Device: Quest 3

**Issue Description**
Passing valid audio samples (duplexed microphone) to `iplBinauralEffectApply` always outputs silence, even when `spatialBlend` is set to `0.0`, ~~which should just be a passthrough~~ (nvm, mono input doesn't trigger this).

**Steps To Reproduce**
1. Create context, default hrtf, binaural effect, mono input, stereo output buffers
2. In audio callback, read samples into input
3. Invoke `iplBinauralEffectApply` with the hrtf.
4. Manually / otherwise deinterleave into the output buffer

The result is silence (validated programmatically, all samples precisely 0.0). Params are as follows:
```c
IPLBinauralEffectParams params = {
        .direction = { 1.0f, 0.0f, 0.0f },
        .interpolation = IPL_HRTFINTERPOLATION_NEAREST,
        .spatialBlend = 1.0f, // or any value
        .hrtf = ipl_hrtf, // Default hrtf
        .peakDelays = NULL,
}; 
```

**Comment by cshenton** [comment] 2024-03-17 02:45
The issue was caused by incorrect usage of the API in the official documentation.

![image](https://github.com/ValveSoftware/steam-audio/assets/14693516/b6468692-12fa-4ea3-bc34-2cf6e59e94d1)

No volume field is being set here, it needs to be set to `1.0` otherwise the stream will just output silence (I don't remember that field last time I used SteamAudio). Leaving the issue open as this is a documentation bug.

**Comment by nisehime** [comment] 2024-03-17 06:39
Should have been fixed? https://github.com/ValveSoftware/steam-audio/pull/309

**Comment by lakulish** [comment] 2024-03-20 23:26
@cshenton This documentation issue was fixed in #309, so I'm closing this issue.

**Closed by lakulish** 2024-03-20 23:26 UTC

**Comment by nisehime** [comment] 2024-03-21 09:16
@lakulish 
I think the issue is that it was not reflected on github pages doc

**Comment by cshenton** [comment] 2024-03-22 10:30
Yes, on several different pages on the github pages documentation the incorrect usage is shown. This is what I was referring to.

**Comment by lakulish** [comment] 2024-03-22 17:18
The documentation in the `gh-pages` branch will be updated when the next official release is made, which I plan to do soon.
