### ISSUE TITLE
Extremely loud screeching error - Unity Plugin

### ISSUE THREAD

**Issue by 8ude** [ValveSoftware/steam-audio#176] opened 2021-11-14 21:55 UTC
I was working on an example project when I encountered this catastrophic, screeching feedback/buffer issue.  I have no idea what is causing it - in the last few minutes of this video I go through all of the steam audio components in the scene, as well as the mixer routing.

Unity version 2020.3.20f1
Steam Audio version 4.0.2
Computer Operating system: Windows 10
Audio Device: RME Babyface ProFS

WARNING - TURN VOLUME WAY WAY DOWN BEFORE VIEWING VIDEO
https://drive.google.com/file/d/1rlA7KPOXfTtnjmzlILSPupzCw5N33SRj/view?usp=sharing

I'm cautiously attempting to reproduce, but am not yet able to isolate the cause. It seems to happen at random, but may have something to do with the reverb. Baked reverb is more volatile than realtime.

Here's the Unity project if someone wants to look at it.

https://drive.google.com/file/d/1X5W3ExtVvS_wShC918G1ta8wUXGrVbEA/view?usp=sharing

**Comment by 8ude** [comment] 2021-11-14 22:14
I'm cautiously attempting to reproduce, but not yet able to isolate the cause. 

It first occurred when I was testing various pathing options with baked probes

**Comment by 8ude** [comment] 2021-11-14 22:37
With more testing, it appears to have something to do with the reverb. Baked reverb is more volatile than realtime. 

Here's the Unity project if someone wants to look at it.

https://drive.google.com/file/d/1X5W3ExtVvS_wShC918G1ta8wUXGrVbEA/view?usp=sharing

**Comment by lakulish** [comment] 2023-05-23 18:51
@8ude I was unable to reproduce the issue in the Unity project you shared. Maybe I just need to move the listener to the correct position to trigger it, do you have a specific point where the issue can be reproduced? Also, I noticed in the video that the pathing probe batch is not set, but it is set in the Unity project you shared, so that may have been the cause.

@Oldnice Could you provide a minimal Unreal project that reproduces the issue? Also, your screenshot seems to be from Steam Audio 2.x, do you have a repro case with screenshot in the latest release of Steam Audio? Thanks!

**Comment by Oldnice** [comment] 2023-05-24 06:39
Hey @lakulish,

I have not had this issue in a few months. I've either managed to fix whatever was causing the issue, it's been fixed by a subsequent SteamAudio release, or it requires a very specific turn of events to occur.

**Closed** 2023-06-05 16:55 UTC
