### ISSUE TITLE
[Unity Plugin] Pre-Export Scene takes into account disabled gameobject

### ISSUE THREAD

**Issue by peroht** [ValveSoftware/steam-audio#91] opened 2019-05-07 08:25 UTC
When having a gameobject (wall) infront of an audio source and using Pre-Export Scene the occlusion works as expected. When disabling the same gameobject and hitting Pre-Export Scene again the occlusion is still active. Deleting the wall and hitting Pre-Export Scene disables the occlusion. 

Is this intended?

**Comment by lakulish** [comment] 2019-05-09 22:46
Thanks, this is not intended behavior, and is actually a bug. (It's not consistent with how dynamic geometry works; when dynamic objects are disabled they stop interacting with sound.) We have a potential fix for this, which will be included in the next release of Steam Audio.

**Comment by peroht** [comment] 2019-05-10 12:26
Excellent. Looking forward to it.

**Closed** 2020-04-22 01:38 UTC
