### ISSUE TITLE
[Unity] Steam Audio + FMod 2.01 Attenuation/Occlusion/Reflection broken

### ISSUE THREAD

**Issue by stepperman** [ValveSoftware/steam-audio#139] opened 2020-12-16 22:05 UTC
I'm trying to implement Steam Audio together with FMOD 2.01. So far sounds work and binaural works as well but what doesn't work is any attenuation (all sound plays at the same volume at every single distance) and the reflections/occlusion don't work.

I've exported the scene and put a `SteamAudioSource` on it, but it simply refuses to work.

Is this a problem with FMod 2.0?

**Comment by JFuellem** [comment] 2020-12-29 17:44
Same here. 2.00.10 kind of works, but Unity crashes all the time as soon as everything is set up correctly, but at least after moving phonon_fmod once back an forth from the two plugin destinations, which you also have to do, because fmod searches for another path, it works.
Had no luck with any version above. Binaural always works but everything else fails...

**Comment by stepperman** [comment] 2021-01-01 19:37
I downgraded to the latest version of FMOD 1.... whatever it was and made an entirely new Unity project to test it out. It actually started working for the first 20 minutes or so, until it suddenly broke for no reason at all.

I've sadly resorted to using Resonance Audio, another fix would just be to use to use the Unity Audio but I have many gripes with it.

**Comment by JFuellem** [comment] 2021-01-02 17:07
It now works on my end after trying for hours. I'm with FMOD 2.01.05 and Unity 2020.1.17f1. It didn't work with the default camera. So after deleting it and adding FMOD listener and Steam Audio Listener (and Unity listener for some reason it stops working if I remove it...) it works for now. Had it running for a few days and hours. Even the Unity Crash I experienced earlier doesn't occur - yay.
There is some bug somewhere and I wish I could know where it is...

**Comment by lakulish** [comment] 2021-01-05 21:09
Hi @stepperman @JFuellem 

Could you provide a minimal project that reproduces the issue? We'll need both the FMOD Studio and Unity projects to diagnose. This is certainly odd behavior, and even if it seems to be working, I'd like to make sure. Thanks.

**Comment by JFuellem** [comment] 2021-01-07 16:42
Here is a test project.
Funnily enough it worked on the first try now. But it still just works with the unity audio listener attached.
And this project also crashes on my machine. I don't know why the other one described above doesn't. I've seen a few people having this error too. Bad access violation of some sort.
In this project I have to move phonon_fmod out of the fmod plugins folder press play and stop and then putting it back to the fmod plugins folder. Then Unity doesn't crash as long as it's open.
Additionally I had to replace some code provided to fix the assembly suffix error or else it also doesn't work.
[https://www.dropbox.com/s/qw585qczwaxvjck/SteamAudio_bugreport20210107.zip?dl=0](url)

**Comment by JFuellem** [comment] 2021-01-14 18:23
And now my other project also starts to crash unity when it is under intense load. In the crash log, it always says it cannot access a certain address coming from phonon_fmod. Unfortunately, I don't have the time to recreate this error in an example project...
It's very weird that this changes from day to day so there is probably some kind of incompatibility with my system.

**Comment by MonSell** [comment] 2021-01-17 10:25
Hi @lakulish
I'm using Unity 2019.4.17f1 (LTS) and FMOD Studio 2.00.10, not getting any crashes. 

So far Baked Indirect partially works, the sound reflects in the environment but abruptly ends, which make it sound very unnatural to me. The sound should continue to bounce even when the sound effect duration is over!

Both Physics-Based Attenuation and Air Absorption doesn't seem to work. However using the Distance Attenuation from the FMOD Spatializer does work (following the instructions from: https://valvesoftware.github.io/steam-audio/doc/phonon_fmod.html#occlusion-mode)

Occlusion seems to not work either. I haven't thoroughly tested it yet though.

I could send you my project but it's unfortunately quite large. It would be awesome if you guys could fix these issues though :)

**Comment by JFuellem** [comment] 2021-03-22 18:42
For me almost everything works now.
My error was, that I just moved phonon_fmod into the new plugin directory and not everything. Moving everything resolved the crash.
Everything is working now. As long as I use FMOD Event emitters, which is another problem for another issue...

**Comment by futurecreep-dev** [comment] 2021-07-18 16:13
I found a fix for direct occlusion, attenuation not working. This is for Steam Audio 2.0-beta.20 (I also upgraded FMOD to 2.02.01 "early access" but I don't think it's related).

In SteamAudioSource.cs in Update() there should be a line
`var listener = managerData.componentCache.AudioListener();`
Change it to
`var listener = managerData.componentCache.SteamAudioListener();`

It is a quick and dirty fix - if someone finds something cleaner please post it. Adding an Unity Audio Source had not worked but I haven't looked into it any deeper.

**Comment by lakulish** [comment] 2021-07-29 17:56
@futurecreep-dev That was indeed one of the issues we fixed in the latest release!

This issue should be fixed in the latest release, available here: https://github.com/ValveSoftware/steam-audio/releases/tag/v4.0.0.

**Closed by lakulish** 2021-07-29 17:56 UTC
