### ISSUE TITLE
Only one dynamic mesh works in the scene if it’s on an imported FBX

### ISSUE THREAD

**Issue by Julianx9000** [ValveSoftware/steam-audio#174] opened 2021-10-29 22:17 UTC
- Using Unity 2020.3.14 & Steam Audio v.4.0.2
- If I import geometry from an external 3D package such as blender or Maya, I am unable to use more than one dynamic mesh in the scene. Multiple meshes will be exported as dynamic (with the Steam Audio Geometry & Dynamic Object component) but only one will occlude audio and influence the reverb. Generally this is the last one exported as dynamic.  It doesn’t matter if the FBX has multiple meshes or just one.  It’s the same every time
- Using the default Unity cubes as dynamic objects works correctly.  I can export any number of Dynamic objects without any problems.  There is no shortage of the number of dynamic meshes that I can make with the built in primitives.
- If I combine imported meshes with unity cubes, I can use as many cubes as I want but I'm still limited to only one working imported mesh/game object as a dynamic object.

Thank you so much for taking a look into this strange bug!  Beyond this bug, I have been really enjoying Steam Audio!

**Comment by achandak** [comment] 2021-12-17 20:27
Hey @Julianx9000 - Sorry for late response. I tried to reproduce the issue with FBX meshes but they behave as expected when marked as dynamic objects. Make sure to export the scene again after marking your FBX meshes as dynamic objects, they might still be part of static mesh if you did not export the scene again. I assumed you are using default ray tracer and followed the steps here - https://valvesoftware.github.io/steam-audio/doc/unity/dynamic-object.html Also, see the Note in the documentation above.

If that does not help, can you share a small standalone project where we can repro this issue or may be FBX model you used. Thanks.

**Comment by lakulish** [comment] 2023-05-22 18:37
Closing this issue since we haven't been able to reproduce it.

**Closed by lakulish** 2023-05-22 18:37 UTC
