### ISSUE TITLE
Facing crashes every time I try to run the game in Unity

### ISSUE THREAD

**Issue by Xapu1337** [ValveSoftware/steam-audio#184] opened 2022-01-18 10:40 UTC
Hey, I have an issue where my editor will crash every time I try to run it.
More details can be found in the attached crash log as in I did nothing special but just followed the getting started in the docs
[Editor.log](https://github.com/ValveSoftware/steam-audio/files/7888341/Editor.log)

**Comment by Xapu1337** [comment] 2022-01-18 13:58
Update: removing AudioClip.Stop() from FixedUpdate seems to fix is but now I have a new error..
[Editor.log](https://github.com/ValveSoftware/steam-audio/files/7889580/Editor.log)
.

**Comment by vTimeMaca** [comment] 2022-03-10 18:42
Think I figured this out.

once the scene is exported via steam audio menu, it creates a scene view window gizmo.
that, has to encapsulate an area with reverb/reflection/steam audio source elements within it.
if you generate over an area where there are none, it creates..... 0 probes.
0 then gets passed through to the internal dll method and results in an arithmetic error, and a crash in the unity editor.
presumably because you can't divide by 0.

**Comment by lakulish** [comment] 2022-04-06 00:53
@Xapu1337 @vTimeMaca Can you provide a crash dump or a minimal test scene/project? That will help us reproduce the issue faster. Thanks!

**Comment by lakulish** [comment] 2022-07-05 20:13
We've just released Steam Audio 4.1.0, which includes various crash fixes: https://github.com/ValveSoftware/steam-audio/releases/tag/v4.1.0.

Try it out and let us know if these crashes persist in the new version.

**Comment by Xapu1337** [comment] 2022-07-16 08:14
> @Xapu1337 @vTimeMaca Can you provide a crash dump or a minimal test scene/project? That will help us reproduce the issue faster. Thanks!
Thanks for the update! Real-time audio now works flawlessly! I will be trying out baked audio soon, but I have a question, do you know why it says that "No OpenCL Device is found"? I have a 3060 and it should be capable of

**Comment by kisak-valve** [comment] 2022-08-19 18:22
Closing per the last couple comments.

**Closed by kisak-valve** 2022-08-19 18:22 UTC
Labels: Need Retest
