### ISSUE TITLE
FMOD/SteamAudio/Unity Integration Issues

### ISSUE THREAD

**Issue by vioaudio** [ValveSoftware/steam-audio#107] opened 2019-11-22 00:32 UTC
Hello, if you have experience successfully setting up FMOD w SteamAudio as a plug-in, which is then integrated into a Unity Project which also has SteamAudio as a plug in, I’d appreciate your assistance.

If I add FMOD or SteamAudio Listener or Emitter Components, I keep getting this error:

SystemNotInitializedException: [FMOD] Initialization failed : Loading plugin 'phonon_fmod' from 'C:/x/x/x/x/Assets/Plugins/FMOD/lib/win/X86_64/phonon_fmod.dll' : ERR_FILE_NOTFOUND : File not found.

FMODUnity.RuntimeManager.get_Instance () (at Assets/Plugins/FMOD/src/Runtime/RuntimeManager.cs:113) FMODUnity.RuntimeManager.get_StudioSystem () (at Assets/Plugins/FMOD/src/Runtime/RuntimeManager.cs:127) FMODUnity.RuntimeManager.AddListener (FMODUnity.StudioListener listener) (at Assets/Plugins/FMOD/src/Runtime/RuntimeManager.cs:330) FMODUnity.StudioListener.OnEnable () (at Assets/Plugins/FMOD/src/Runtime/StudioListener.cs:18)

Placing the .dll file in the location that is listed above results in an additional error about there being a duplicate

**Comment by achandak** [comment] 2019-11-27 23:24
This seems to be because of a change in FMOD Studio 2.0 and onwards. These newer versions of FMOD Studio expect phonon_fmod.dll to be in a different location (under Plugins/FMOD/lib/) as compared to older versions (which expected the DLL to be under Plugins/).

Can you try the following:

1. Move Plugins/x86_64/phonon_fmod.dll to Plugins/FMOD/lib/win/x86_64.
2. Copy Plugins/x86_64/phonon.dll to Plugins/FMOD/lib/win/x86_64.

Let us know if this resolves the issue. If it doesn't, provide us with the complete console/log output so we can see what's going on.

**Comment by Sorgon** [comment] 2020-09-30 10:00
> This seems to be because of a change in FMOD Studio 2.0 and onwards. These newer versions of FMOD Studio expect phonon_fmod.dll to be in a different location (under Plugins/FMOD/lib/) as compared to older versions (which expected the DLL to be under Plugins/).
> 
> Can you try the following:
> 
> 1. Move Plugins/x86_64/phonon_fmod.dll to Plugins/FMOD/lib/win/x86_64.
> 2. Copy Plugins/x86_64/phonon.dll to Plugins/FMOD/lib/win/x86_64.
> 
> Let us know if this resolves the issue. If it doesn't, provide us with the complete console/log output so we can see what's going on.

I have the same problem but in the built version. In editor it works fine, as I followed the steps you suggested.

In the built version I am getting the following error:
`SystemNotInitializedException: [FMOD] Initialization failed : Loading plugin 'phonon_fmod' from 'C:/BUILD/GameClientAdmin/GameClientAdmin_Data/Plugins/phonon_fmod.dll' : ERR_FILE_NOTFOUND : File not found.
  at FMODUnity.RuntimeManager.get_Instance () [0x0010e] in <80f8846ee694421f89d7d68280d28801>:0 
  at FMODUnity.RuntimeManager.PathToGUID (System.String path) [0x0001e] in <80f8846ee694421f89d7d68280d28801>:0 
  at FMODUnity.RuntimeManager.GetEventDescription (System.String path) [0x00000] in <80f8846ee694421f89d7d68280d28801>:0 
  at FMODUnity.StudioEventEmitter.Lookup () [0x00000] in <80f8846ee694421f89d7d68280d28801>:0 
  at FMODUnity.StudioEventEmitter.Play () [0x0002c] in <80f8846ee694421f89d7d68280d28801>:0 
  at FMODUnity.StudioEventEmitter.HandleGameEvent (FMODUnity.EmitterGameEvent gameEvent) [0x00009] in <80f8846ee694421f89d7d68280d28801>:0 
  at FMODUnity.EventHandler.OnEnable () [0x00000] in <80f8846ee694421f89d7d68280d28801>:0 `

The problem is that FMOD expects the file to be in C:/BUILD/GameClientAdmin/GameClientAdmin_Data/Plugins/phonon_fmod.dll but it is in fact in C:/BUILD/GameClientAdmin/GameClientAdmin_Data/Plugins/x86_64/phonon_fmod.dll

Please advise.

**Comment by lakulish** [comment] 2020-10-01 19:41
Which specific version of FMOD Studio are you using? And which version of the FMOD Studio Unity integration? This will help us repro the issue exactly. Thanks.

**Comment by Sorgon** [comment] 2020-10-02 12:40
Sorry. I talked with someone from FMOD, and they suggested upgrading FMOD Unity integration. Then the problem was fixed.

**Comment by lakulish** [comment] 2021-07-29 17:57
This issue should be fixed in the latest release, available here: https://github.com/ValveSoftware/steam-audio/releases/tag/v4.0.0.

**Closed by lakulish** 2021-07-29 17:57 UTC
