### ISSUE TITLE
No sound heard if audio source clips through solid geometry

### ISSUE THREAD

**Issue by lakulish** [ValveSoftware/steam-audio#12] opened 2017-02-27 18:40 UTC
Example here: http://steamcommunity.com/app/596420/discussions/0/133258092241133882/

**Comment by AndersMalmgren** [comment] 2017-02-27 18:56
Just to be clear, the entire sound engine crashes. No sound from any audiosource is heard after this point.

**Comment by AndersMalmgren** [comment] 2017-03-08 15:50
Any ETA when this will be fixed now that its reproduced?

**Comment by achandak** [comment] 2017-03-08 18:24
The fix will be available with next release. Until then, consider using raycast occlusion instead of partial occlusion to sidestep the issue.

**Comment by lakulish** [comment] 2017-03-16 23:27
We have just released Steam Audio v2.0-beta.2. This issue should be fixed now, can you try out the latest version and let us know if you're still facing this issue?

Get the latest version from https://valvesoftware.github.io/steam-audio/.

**Comment by AndersMalmgren** [comment] 2017-03-17 09:42
Im getting 


> Environment and Environmental Renderer component must be attached when reflections are enabled or direct occlusion is set to Raycast or Partial.
> UnityEngine.Debug:LogError(Object)
> Phonon.PhononSource:Awake() (at Assets/Phonon/Simulator/PhononSource.cs:47)
> 

after update. This is my listener

![settings](http://i.imgur.com/MABaHWf.png)

**Comment by AndersMalmgren** [comment] 2017-03-17 09:52
We load player dynamic att scene start if that could be the problem

**Comment by AndersMalmgren** [comment] 2017-03-17 09:59
Yepp, its most definitely connected to that. You need to make sure that the library works with no listener in  the scene. Beta 1 did this

**Comment by lakulish** [comment] 2017-03-17 16:23
You can move the Environment and Environmental Renderer components to an empty GameObject that you create, which is not dynamically loaded. That should resolve the issue.

We will update the documentation to clarify this.

**Comment by AndersMalmgren** [comment] 2017-03-17 16:25
So it does not need to be attached to the Audio listener object at all?

**Comment by lakulish** [comment] 2017-03-17 16:29
Nope, it just needs to be present somewhere in the scene.

**Comment by AndersMalmgren** [comment] 2017-03-17 16:31
ok tried that, now I get.

> NullReferenceException: Object reference not set to an instance of an object
> Phonon.PhononSource.UpdateRelativeDirection () (at Assets/Phonon/Simulator/PhononSource.cs:117)
> Phonon.PhononSource+<EndOfFrameUpdate>c__Iterator0.MoveNext () (at Assets/Phonon/Simulator/PhononSource.cs:100)
> UnityEngine.SetupCoroutine.InvokeMoveNext (IEnumerator enumerator, IntPtr returnValueAddress) (at C:/buildslave/unity/build/Runtime/Export/Coroutines.cs:17)
> UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
> Phonon.PhononSource:OnEnable() (at Assets/Phonon/Simulator/PhononSource.cs:53)

**Comment by AndersMalmgren** [comment] 2017-03-17 16:35
Its because you do, 

                listener = FindObjectOfType<AudioListener>();

in awake

**Comment by achandak** [comment] 2017-03-17 16:40
Thanks for catching this.

Yup, lazy load this and you should be fine. We will fix this on our end and see if there are similar issues elsewhere in the plugin.

**Comment by AndersMalmgren** [comment] 2017-03-17 16:44
Cool, let me know how it goes. I dont want to mess with vendor code, will be merge hell

**Comment by AndersMalmgren** [comment] 2017-03-17 16:53
This does the trick, dont know if calling FindObject every frame until it exists is elegant enough for production code
```csharp
        private void UpdateRelativeDirection()
        {
            if ((listener = listener ?? FindObjectOfType<AudioListener>()) == null) return;

            sourcePosition = Common.ConvertVector(transform.position);
            listenerPosition = Common.ConvertVector(listener.transform.position);
            listenerAhead = Common.ConvertVector(listener.transform.forward);
            listenerUp = Common.ConvertVector(listener.transform.up);
        }
```

**Comment by AndersMalmgren** [comment] 2017-03-17 16:56
yield return new WaitForEndOfFrame();  creates some garbage. Better to cache the WaitForEndOfFrame in a private member

**Comment by bddckr** [comment] 2017-03-17 17:05
@AndersMalmgren `yield return null;` is the same as `yield return new WaitForEndOfFrame();` and means you don't need a private cached variable 😄

**Comment by AndersMalmgren** [comment] 2017-03-17 17:32
I read somewhere they fire at different places in a frames lifetime.

**Comment by achandak** [comment] 2017-03-17 18:23
@AndersMalmgren - that is pretty much the fix we are pushing shortly. Are you seeing any other issue after you make that change?

**Comment by AndersMalmgren** [comment] 2017-03-17 18:42
I had to leave the office for the evening, but I'll try to reproduce the crash bug tomorrow

**Comment by bddckr** [comment] 2017-03-17 19:02
@AndersMalmgren [You're right.](http://answers.unity3d.com/answers/755208/view.html) But I think in this case `null` should be fine?

**Comment by AndersMalmgren** [comment] 2017-03-17 19:14
If next update is dependant on it then you should not use null

http://answers.unity3d.com/questions/755196/yield-return-null-vs-yield-return-waitforendoffram.html

**Comment by achandak** [comment] 2017-03-17 20:06
Last time we checked, WaitForEndOfFrame() was needed to get correct camera information in a VR setup.

We have updated 2.0-beta.2 release with couple of hotfixes.

**Comment by AndersMalmgren** [comment] 2017-03-17 20:19
Hey guys. I can not reproduce crash bug. So thats good. But the fall off is way too aggressive, we cant use it as it is sadly. Even with a Indirect Mix Fraction at 5 the sound falls away almost right away after rounding a corner. Also a Indirect Mix Fraction of 5 changes the characteristics of the sound too much.

Hope you guys are wokring on that because this is really a nice tool otherwise. Great work!

**Comment by achandak** [comment] 2017-03-20 19:00
@AndersMalmgren - I will close this issue out if the clipping thins is resolve. I have posted on your Forum post on Aggressive cutoff. Moving the discussion there.

**Closed** 2017-03-20 22:10 UTC
