### ISSUE TITLE
Spatial blend briefly incorrect in unity

### ISSUE THREAD

**Issue by zulubo** [ValveSoftware/steam-audio#118] opened 2020-05-17 20:51 UTC
When an audio source plays sound for the first time, spatial blend seems to default to zero and take a moment to update to the value set on the audioSource component. This results in a moment of very loud audio playing from even distant sources. Most noticeable when an audiosource plays well into a level load, e.g. an enemy spawns in and fires their gun.

**Comment by achandak** [comment] 2020-05-18 16:00
@zulubo - Can you paste screenshot of your AudioSource component and SteamAudioSource component so we can replicate the issue?

**Comment by zulubo** [comment] 2020-05-18 16:16
Actually managed to fix this, seems like having Play On Awake enabled with no audioclip set in the component causes this to happen. Disabling Play On Awake resolves it.

Here's a screenshot of an Audiosource component that has the bug:

![image](https://user-images.githubusercontent.com/29665945/82235877-27747680-98e8-11ea-9254-3b2589377e77.png)

Also note, I'm in unity 2019.10 if that matters

**Comment by achandak** [comment] 2020-05-18 16:24
What version of Steam Audio are you using?

**Comment by zulubo** [comment] 2020-05-18 16:47
Latest beta release. Those steps sound right. I'll see if I can repro in an empty project.

**Comment by zulubo** [comment] 2020-05-18 16:55
yup, was able to reproduce bug in a new project. Here's a package containing my setup 
[SpatializationBug.zip](https://github.com/ValveSoftware/steam-audio/files/4645483/SpatializationBug.zip)

**Comment by achandak** [comment] 2020-06-05 21:12
@zulubo - Thanks for sharing a project. We looked at the bug and following is happening:

- When Play on Awake is set with no Audio Clip, Unity is sending spatial blend value of 0 and distance attenuation of 1. 
- Next, when you set the Audio Clip and call Play, correct values of spatial blend of 1 and distance of attenuation of ~.03 are sent.
- Steam Audio correctly blends attenuation of 1 to .03 for smooth transition over a few frames, so you hear part of audio clip with distance attenuation higher than .03

The problem is that Unity should either not call the spatializer when there is no Audio Clip or should send the correct parameters. We are going to send a bug report to Unity and let them know.

Your workout seems sensible, so continue using that until there is an update on this from Unity. I will post an update here or in Release Notes when this issue is resolved by Unity, but closing it here.

**Closed by achandak** 2020-06-05 21:12 UTC

**Comment by zulubo** [comment] 2020-06-05 21:17
Cool, thanks for looking into it!
