### ISSUE TITLE
Invalid memory free on iplCreateEnvironmentalRenderer(...)

### ISSUE THREAD

**Issue by aegroto** [ValveSoftware/steam-audio#75] opened 2018-09-14 11:59 UTC
It seems like iplCreateEnvironmentalRenderer causes an invalid pointer to be freed.
```

*** Error in `./main': free(): invalid pointer: 0x000000000119f758 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x777e5)[0x7f378b1c07e5]
/lib/x86_64-linux-gnu/libc.so.6(+0x8037a)[0x7f378b1c937a]
/lib/x86_64-linux-gnu/libc.so.6(cfree+0x4c)[0x7f378b1cd53c]
steamaudio/lib/Linux/x64/libphonon.so(_ZN3ipl6Memory4freeEPv+0x34)[0x7f378b56ef54]
steamaudio/lib/Linux/x64/libphonon.so(_ZN3ipl9allocatorINS_16SimulationThreadEE9constructIS1_JRSt10shared_ptrINS_11EnvironmentEERKNS_17RenderingSettingsERiRSt8functionIFvvEESF_EEEvPT_DpOT0_+0x205)[0x7f378b5db505]
steamaudio/lib/Linux/x64/libphonon.so(_ZN3ipl21EnvironmentalRendererC2ESt10shared_ptrINS_7ContextEES1_INS_11EnvironmentEERKNS_17RenderingSettingsENS_11AudioFormatESt8functionIFvvEESC_+0x292)[0x7f378b5d9b92]
steamaudio/lib/Linux/x64/libphonon.so(_ZN3ipl9allocatorINS_21EnvironmentalRendererEE9constructIS1_IRSt10shared_ptrINS_7ContextEERS4_INS_11EnvironmentEERNS_17RenderingSettingsERNS_11AudioFormatERPFvvESH_EEEvPT_DpOT0_+0x18d)[0x7f378b5f358d]
steamaudio/lib/Linux/x64/libphonon.so(iplCreateEnvironmentalRenderer+0x19b)[0x7f378b5f2f7b]
./main[0x400ce9]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0)[0x7f378b169830]
./main[0x4007e9]
======= Memory map: ========
00400000-00402000 r-xp 00000000 08:03 4325455                            /home/lorenzo/Scrivania/Varie/repo/phonon unit test/main
00601000-00602000 r--p 00001000 08:03 4325455                            /home/lorenzo/Scrivania/Varie/repo/phonon unit test/main
00602000-00603000 rw-p 00002000 08:03 4325455                            /home/lorenzo/Scrivania/Varie/repo/phonon unit test/main
01186000-011c0000 rw-p 00000000 00:00 0                                  [heap]
7f3784000000-7f3784021000 rw-p 00000000 00:00 0
7f3784021000-7f3788000000 ---p 00000000 00:00 0
7f378a69c000-7f378a6b2000 r-xp 00000000 08:03 10485937                   /lib/x86_64-linux-gnu/libgcc_s.so.1
7f378a6b2000-7f378a8b1000 ---p 00016000 08:03 10485937                   /lib/x86_64-linux-gnu/libgcc_s.so.1
7f378a8b1000-7f378a8b2000 r--p 00015000 08:03 10485937                   /lib/x86_64-linux-gnu/libgcc_s.so.1
7f378a8b2000-7f378a8b3000 rw-p 00016000 08:03 10485937                   /lib/x86_64-linux-gnu/libgcc_s.so.1
7f378a8b3000-7f378a9bb000 r-xp 00000000 08:03 10486989                   /lib/x86_64-linux-gnu/libm-2.23.so
7f378a9bb000-7f378abba000 ---p 00108000 08:03 10486989                   /lib/x86_64-linux-gnu/libm-2.23.so
7f378abba000-7f378abbb000 r--p 00107000 08:03 10486989                   /lib/x86_64-linux-gnu/libm-2.23.so
7f378abbb000-7f378abbc000 rw-p 00108000 08:03 10486989                   /lib/x86_64-linux-gnu/libm-2.23.so
7f378abbc000-7f378ad35000 r-xp 00000000 08:03 133318                     /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.24
7f378ad35000-7f378af35000 ---p 00179000 08:03 133318                     /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.24
7f378af35000-7f378af3f000 r--p 00179000 08:03 133318                     /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.24
7f378af3f000-7f378af41000 rw-p 00183000 08:03 133318                     /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.24
7f378af41000-7f378af45000 rw-p 00000000 00:00 0
7f378af45000-7f378af48000 r-xp 00000000 08:03 10486995                   /lib/x86_64-linux-gnu/libdl-2.23.so
7f378af48000-7f378b147000 ---p 00003000 08:03 10486995                   /lib/x86_64-linux-gnu/libdl-2.23.so
7f378b147000-7f378b148000 r--p 00002000 08:03 10486995                   /lib/x86_64-linux-gnu/libdl-2.23.so
7f378b148000-7f378b149000 rw-p 00003000 08:03 10486995                   /lib/x86_64-linux-gnu/libdl-2.23.so
7f378b149000-7f378b309000 r-xp 00000000 08:03 10486993                   /lib/x86_64-linux-gnu/libc-2.23.so
7f378b309000-7f378b509000 ---p 001c0000 08:03 10486993                   /lib/x86_64-linux-gnu/libc-2.23.so
7f378b509000-7f378b50d000 r--p 001c0000 08:03 10486993                   /lib/x86_64-linux-gnu/libc-2.23.so
7f378b50d000-7f378b50f000 rw-p 001c4000 08:03 10486993                   /lib/x86_64-linux-gnu/libc-2.23.so
7f378b50f000-7f378b513000 rw-p 00000000 00:00 0
7f378b513000-7f378b9b3000 r-xp 00000000 08:03 7221278                    /home/lorenzo/Scrivania/Varie/repo/phonon unit test/steamaudio/lib/Linux/x64/libphonon.so
7f378b9b3000-7f378bbb3000 ---p 004a0000 08:03 7221278                    /home/lorenzo/Scrivania/Varie/repo/phonon unit test/steamaudio/lib/Linux/x64/libphonon.so
7f378bbb3000-7f378bbb7000 r--p 004a0000 08:03 7221278                    /home/lorenzo/Scrivania/Varie/repo/phonon unit test/steamaudio/lib/Linux/x64/libphonon.so
7f378bbb7000-7f378c0c7000 rw-p 004a4000 08:03 7221278                    /home/lorenzo/Scrivania/Varie/repo/phonon unit test/steamaudio/lib/Linux/x64/libphonon.so
7f378c0c7000-7f378c0d0000 rw-p 00000000 00:00 0
7f378c0d0000-7f378c0f6000 r-xp 00000000 08:03 10486991                   /lib/x86_64-linux-gnu/ld-2.23.so
7f378c2c4000-7f378c2ca000 rw-p 00000000 00:00 0
7f378c2f3000-7f378c2f5000 rw-p 00000000 00:00 0
7f378c2f5000-7f378c2f6000 r--p 00025000 08:03 10486991                   /lib/x86_64-linux-gnu/ld-2.23.so
7f378c2f6000-7f378c2f7000 rw-p 00026000 08:03 10486991                   /lib/x86_64-linux-gnu/ld-2.23.so
7f378c2f7000-7f378c2f8000 rw-p 00000000 00:00 0
7ffcc58d7000-7ffcc58f8000 rw-p 00000000 00:00 0                          [stack]
7ffcc59ad000-7ffcc59b0000 r--p 00000000 00:00 0                          [vvar]
7ffcc59b0000-7ffcc59b2000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]
Aborted (core dumped)
```

I'm executing a simple test case on Kubuntu 16.04 (64 bit), steam audio version is 2.0-beta15.

Test case: https://gist.github.com/aegroto/19621f48183e6b3efa65f4e9659862df

**Comment by lakulish** [comment] 2020-01-22 23:32
We are not able to reproduce this issue with Steam Audio 2.0-beta.17. Can you rebuild your example code with the latest version of the Steam Audio SDK and confirm whether you still encounter the issue? Thanks.

**Comment by kisak-valve** [comment] 2020-02-28 14:48
Closing pending feedback.

**Closed by kisak-valve** 2020-02-28 14:48 UTC
Labels: Need Retest
