### ISSUE TITLE
[4.0.0][Unity] Crash - RadeonRays and only dynamic geometry (none static)

### ISSUE THREAD

**Issue by futurecreep-dev** [ValveSoftware/steam-audio#160] opened 2021-08-10 01:40 UTC
After entering Play mode, sound plays as expected for under 1 sec, then pauses as Editor crashes and the reporter loads; As reporter finishes and Editor is closed/crashed, sound continues for 2-3 very short segments.
Builds crash instantly after loading and only the segments (shorter) can be heard as the crash reporter finishes.

I did not try any baking. Everything works as expected with the other ray tracers and default convolution or TAN. The scene only uses dynamic objects/geometry.

I have found no way to make it work, it always crashes as described.

Changes I've tried:
Rays, bounces, duration, ambisonic order, compute units, HRTFs
DX11 or Vulkan.

As a note RadeonRays worked in 2.0b20, same project, similar settings.

Unity 2021.1.15f1, FMOD 20.02.01, Windows 10 64-bit (20H2, Pro)
AMD RX580 8GB driver 21.6.1 (latest recommended) also tried 21.7.2 (latest optional)

I have privately sent crash logs and the dump file to @lakulish (Subject "(GitHub issue) Steam Audio RadeonRays crash logs")

Pic of settings, don't think it matters as no combinations worked:
(click for full size)
<img src="https://user-images.githubusercontent.com/87613086/128792804-443a31ab-3ab3-49c8-9190-5800f0e9c871.PNG" width="80">

**Comment by lakulish** [comment] 2021-08-12 18:41
Thanks for providing the crash dumps and logs.

Note that the Radeon Rays scene type in Steam Audio does not currently support dynamic objects (neither in 2.0-beta.20 nor in 4.0.0).

It looks like the crash is occurring because no static meshes were provided to Radeon Rays. We will attempt to reproduce the issue and fix the crash.

**Comment by lakulish** [comment] 2021-08-13 17:31
We are able to reproduce this behavior. A fix will be included in the next patch release.

**Comment by lakulish** [comment] 2021-09-15 22:32
This issue is fixed in the latest patch release: https://github.com/ValveSoftware/steam-audio/releases/tag/v4.0.1.

**Closed by lakulish** 2021-09-15 22:32 UTC
