### ISSUE TITLE
Unity crash when entering playmode with any audio source that has real time reverb enabled.

### ISSUE THREAD

**Issue by antondoggo** [ValveSoftware/steam-audio#192] opened 2022-03-14 23:34 UTC
Unity is crahsing when i enter play mode if there is an audio source with real time reverb enabled. My scene mode is set to Unity, I am using Unity 2020.3.27f1, FMOD 2.02.04 and steam audio 4.0.3.
I can find another post where it is mentioned to be fixed. Any ideas what could be the issue ?
I have followed every step in the manual.

**Comment by constantinpopp** [comment] 2022-04-05 19:02
i had unity crashes with reverb when the game object's audio geometry wasn't properly tagged, the scene geometry not properly exported or the scene geometry asset assigned to the same asset as the audio probes. it's worth checking those aspects even if you use realtime reverb. alternatively try the baked reverb. i'd also recommend looking at the steam audio documentation for unity in tandem with the one for fmod.

**Comment by lakulish** [comment] 2022-04-06 00:58
@antondoggo @MarceloThunder Can you provide a crash dump or minimal test scene/project? That will help us reproduce the issue faster. Thanks!

@antondoggo Also, the Unity ray tracer is not intended to be used for real-time reverb simulation, since it's not performant enough. Do the Default or Embree ray tracers not work for you? If so, is it due to crashes/bugs, or is there some missing functionality you need for your project?

@MarceloThunder Can you provide more details on the materials you've configured for the walls as well as the door?

**Comment by lakulish** [comment] 2022-07-05 20:15
We've just released Steam Audio 4.1.0, which includes various crash fixes: https://github.com/ValveSoftware/steam-audio/releases/tag/v4.1.0.

Try it out and let us know if these crashes persist in the new version.

**Comment by kisak-valve** [comment] 2022-08-19 18:25
Closing pending feedback.

**Closed by kisak-valve** 2022-08-19 18:25 UTC
Labels: Need Retest
