### ISSUE TITLE
Costum HRTF wont't load

### ISSUE THREAD

**Issue by SilkeKleinerBogen** [ValveSoftware/steam-audio#80] opened 2018-11-26 12:01 UTC
Hey there,
I am using the new version of the steam Audio plugin with costum HRTF.
I did everything described in the HTML file. Checked it several times, deinstalled and installed all plugins several times, but my costum HRTF won't load. When I type a random name for HRTF the "not found" error occurs, when using the name of a sofa file, no error occurs (as expected), but the used HRTFs are not my costum ones. To verify my problem, I used HRTF with time delays and also used HRTF with only zeros in it, but it seems that it doesn't change to my costum HRTF, instead using the default ones (but no error occurs, saying that the system switched back to default).
I am using simpleFreeFieldHRIR Sofa conventions, as explained in the HTML file.
Does anyone have a clue what I am doing wrong? Or is it a common error?
Thanks for your help.

**Comment by achandak** [comment] 2018-11-26 16:32
Are you using C API or Unity plugin?

If you are using Unity plugin - did you follow all the instructions [here](https://valvesoftware.github.io/steam-audio/doc/phonon_unity.html#using-custom-hrtfs)?

**Comment by SilkeKleinerBogen** [comment] 2018-11-26 17:02
I am using the Unity Plugin. I am sorry I didn't mention that. 
Yes, I did, checked everything several times, created plenty of Test-Projekts. Well, no error occurs, but those HRTFs are definitely not ours ;-). We used an SimpleFreeField Sofa file with only zeros as data. Using those HRTFs (HRIRs) no sound should be played. But it is still there. It is obvious, that we still listen with the default HRTF set, no matter which HRTF we try to use ;-).
I know this is not a page for such typ of questions, but we were not sure whether it is our fault or not, plus maybe someone else has the same trouble. 
Thanks for trying to help.

**Comment by achandak** [comment] 2018-11-26 17:10
Can you provide a screenshot of Steam Audio Manager? Also, if you want to share the HRTF dataset, we can take a look it on our end. 

We have tested it on different HRTF datasets, copy [this](http://sofacoustics.org/data/database/mit/) one in StreamAssets folder and check if that works.

**Comment by SilkeKleinerBogen** [comment] 2018-11-26 18:21
[Sofa_Screenshot.zip](https://github.com/ValveSoftware/steam-audio/files/2616814/Sofa_Screenshot.zip)
Unfortunately, it did not work either. I am using the same conventiones etc. I am missing something, but can't figuer out what it is. 
The zip contains the SOFA file and a screenshot.

**Comment by achandak** [comment] 2018-11-26 18:30
Your Steam Audio Manager settings seem to be correct. You hear no change if you change Current SOFA File after hitting play?

Have you followed the following two steps:
- Under Spatializer Plugin, choose Steam Audio. ([doc](https://valvesoftware.github.io/steam-audio/doc/phonon_unity.html#unity-project-settings))
- Check spatializer and set source to 3D. ([doc](https://valvesoftware.github.io/steam-audio/doc/phonon_unity.html#d-audio))

The only think I can think of after this is for you to upload your Unity project for me to take a look.

**Comment by SilkeKleinerBogen** [comment] 2018-11-27 13:52
Yes, I did those steps. There is no effect when I change HRTF at runtime. I set up a simple sample scene, unfortunately it is too big to upload it here. 
Is there something like machine intern audio device must be this or that (well, the default HRTF renders normal with motion)?
Sorry for bothering you with a private issue.

**Comment by achandak** [comment] 2018-11-27 16:50
We can't reproduce the issue on our end. So, we will need something reproducible for us to look into this further. The next logical step would be to take a look at your project in Unity and see if the same project exhibit this issue on our end.

**Comment by SilkeKleinerBogen** [comment] 2018-11-29 16:07
Hey, 
so we found out, that building the scene and running the builded scene uses the selected HRTF. In Unity its selfe it doesn't do anything. Is it possible that my computer is kind of overloaded (even with a simple sample scene) to change on the fly in Unity? But why does it not use the selected one from the beginning? I am using the whole thing on windows 7, with Unity 2018.2.14f1 and a geforce gtx 1060. Didn't have any overload problems before.

**Comment by songli2017** [comment] 2019-09-25 20:36
Hey,
do you have solved your problem?
I have a similar problem. Software I use: Visual Studio 2019, Unity 2019.2.6, Hololens 1.
I can switch HRTF in run time if I run the program in Unity. Furthermore, I have written a c# script to build a dropdown menu so that it can switch HRTFs in the application. It also works when I run the program in Unity. 
But If I build the program in Hololens, it doesn't work anymore. Only the default HRTF is loaded and the switched customized HRTFs are not be used or loaded.

key code in c# :
..
..
void update()
{
int menuIndex = dropdownMenu.GetComponent<Dropdown>().value;
 this.GetComponent<SteamAudio.SteamAudioManager>().currentSOFAFile = menuIndex;
}
..
..

**Comment by achandak** [comment] 2019-11-13 23:34
@SilkeKleinerBogen - Let us know if there a minimal project you can share that reproduces the issue.

@songli2017 - We do not support UWP. Our understanding is that you will need UWP support in Steam Audio for it to work on Hololens.

**Comment by lakulish** [comment] 2020-05-13 22:44
@SilkeKleinerBogen @songli2017 I'm closing this issue out; let us know if you continue to face this issue in the latest release of Steam Audio, and we'll reopen it.

**Closed by lakulish** 2020-05-13 22:44 UTC
