### ISSUE TITLE
(Unity) Can't Import Steam Audio v4.4.1 - Endless Import Loop

### ISSUE THREAD

**Issue by ForemanDev** [ValveSoftware/steam-audio#282] opened 2023-10-24 20:13 UTC
**System Information**
Please provide the following information about your system:
- Steam Audio version: 4.4.1 (Unity)
- Unity version: 2022.3.10f1
- Operating System and version: Windows 10

**Issue Description**
It is not possible for me to import Steam Audio v4.4.1 because this causes the Unity Editor to get stuck in an endless import loop. v4.4.0 does not have this problem. Over and over again a dialog pops up that says "Reloading Domain", then "Importing Assets", then "Completing Domain", and this repeats endlessly until I quit Unity. This makes the Unity Editor unusable until Steam Audio v4.4.1 is removed from the project. Luckily I was able to remove the plugin easily using Unity Version Control (Plastic SCM) and my temporary fix is to instead import Steam Audio v4.4.0 which does not have this problem. 

**Steps To Reproduce**
1. Create a new Unity project with Unity v2022.3.10f1
2. Set platform to Android, IL2CPP scripting backend, and ARM64 architecture.
3. Import Bakery GPU Lightmapper (https://assetstore.unity.com/packages/tools/level-design/bakery-gpu-lightmapper-122218)
4. Import Steam Audio v4.4.1 via the .unitypackage (select all assets)
5. Observe endless import loop, which makes Unity unusable.
6. Quit Unity and remove Steam Audio v4.4.1 from the project.
7. Re-open Unity and import Steam Audio older version v4.4.0
8. Observe no issue with v4.4.0

**EDIT:** There appears to be a **conflict with Bakery GPU Lightmapper** only for v4.4.1 but not for v4.4.0. I have edited the above "Steps to Reproduce" and will attach a repro project below.

**Comment by ForemanDev** [comment] 2023-10-24 21:15
@lakulish I have traced the issue to some sort of a conflict with Bakery GPU Lightmapper (a very widely-used baked lighting tool for Unity). I have also updated the "Steps to Reproduce" in the original post.

Here is a link for a repro project for you to test with: https://www.dropbox.com/scl/fi/zo90hpde5c7gnxosrcanl/SteamAudio_v4-4-1_Repro.zip?rlkey=o1ykdovajastm6tioidf5usdx&dl=0

Steps for using the repro project:
1. Unzip the project and add it to Unity Hub.
2. Open the project. NOTE: In Unity Hub, be sure to select 'Android' platform when first opening the project by selecting 'Editor Version' and then 'Android' platform.
3. Import Steam Audio v4.4.1 (via the .unitypackage release)
4. Observe endless import loop.
5. Close Unity (force close if needed).
6. Delete Steam Audio plugin from the project.
7. Import older version Steam Audio v4.4.0
8. Observe no issue.

Could you please help me determine what's wrong here, and how to fix? Is there some sort of assembly definition conflicting with Bakery or something?

**Comment by lakulish** [comment] 2023-10-24 22:30
@ForemanDev Can you try importing `SteamAudio.unitypackage` from v4.4.1, but when the Import dialog box opens, uncheck `Assets/Plugins/SteamAudio/Scripts/Editor/Build.cs`? Let me know if this resolves the issue.

**Comment by ForemanDev** [comment] 2023-10-24 23:54
Yes, excluding 'Build.cs' does solve the issue. Looks like there was an 'InitializeOnLoad' method added to this script in v4.4.1 that might be inadvertently causing the problem?

**Comment by ForemanDev** [comment] 2023-10-24 23:55
> @ForemanDev Can you try importing `SteamAudio.unitypackage` from v4.4.1, but when the Import dialog box opens, uncheck `Assets/Plugins/SteamAudio/Scripts/Editor/Build.cs`? Let me know if this resolves the issue.

@lakulish Yes, excluding 'Build.cs' does solve the issue. Looks like there was an 'InitializeOnLoad' method added to this script in v4.4.1 that might be inadvertently causing the problem?

**Comment by lakulish** [comment] 2023-10-25 00:41
@ForemanDev Yes, looks like the new `InitializeOnLoad` method is somehow causing this issue. We will investigate further, but in the meantime, good to know that the workaround helps.

**Comment by ForemanDev** [comment] 2023-10-25 00:49
Ok, thank you for investigating, @lakulish! The Unity project I linked above should be useful for you to use for testing, as you can observe the issue simply by unzipping that project, opening it, then importing the Steam Audio plugin.

For avoidance of doubt, is it actually a safe workaround to fully delete/exclude 'Build.cs' or will that cause build errors when attempting to build the project?

Or would it be a better workaround to import v4.4.1 while excluding 'Build.cs', then after that import the older 'Build.cs' script from v4.4.0?

**Comment by lakulish** [comment] 2023-10-25 01:05
While the cleaner workaround is to use `Build.cs` from 4.4.0, it only contains code that is used when generating `SteamAudio.unitypackage`, so it should be fine to just leave it out.

**Comment by ForemanDev** [comment] 2023-10-25 01:32
Ok, thank you for clarifying!

**Comment by TsFreddie** [comment] 2023-10-27 02:37
Since #280, we can probably allow developer to toggle SteamAudio manually instead of trying to add the symbols automatically (in case some prefer disabling them on Android only). There probably isn't a reliable way to automatically deal with define symbols unless you are willing to write a config file in project directory which I personally dislike.

How about:

1. Flipping the define symbols to DISABLE_STEAMAUDIO
2. Add a routine to check whether a native plugin exists in current selected platform
3. Call the routine in Inspector OnEnable, if the native plugin does not exists, skip drawing the inspector and prompt with a button to add the define symbol to the current platform
4. And of course add another button under DISABLE_STEAMAUDIO

If this sounds okay I could try to implement it if anyone haven't already been working on this.

**Comment by lakulish** [comment] 2023-10-27 19:01
@ForemanDev We were able to repro the issue, and it wasn't anything specific to Bakery. Steam Audio was not setting the defines in the correct way, causing Steam Audio and Bakery to keep trying to add their defines in an infinite loop. This would have occurred with any plugin that used an `InitializeOnLoad` method to set defines.

We have made a fix for this issue, which will be part of the next release.

@TsFreddie We can take a look at your pull request as well, just in case there's some other use case that our fix may not account for. Thanks!

**Comment by ForemanDev** [comment] 2023-10-27 20:22
@lakulish Thank you so much for fixing this!

**Comment by MaxVRAM** [comment] 2023-11-22 06:10
I've had the same issue while importing Steam Audio v4.4.1 into an existing project.

I can confirm that unchecking `Build.cs` in the import dialogue stops the domain refresh/import loop.

**Comment by churi24** [comment] 2023-11-25 19:29
I've been testing quite a bit today and I noticed the following. If I install SteamAudio in an empty project, it installs fine. However, if I install it in a project that already has post-processing in the built-in pipeline, the installation gets stuck in amn infinite loop. I'm going to try your workaround.

**Comment by RebeccaBieleskiWeta** [comment] 2023-12-04 22:41
I had taken out the Build.cs from my import and that stopping the infinite import loop glitch, but when I merged with main, other individuals starting having infinite import loops as well.

**Comment by lakulish** [comment] 2023-12-18 17:31
We have just released v4.5.0, which contains a fix for this issue: https://github.com/ValveSoftware/steam-audio/releases/tag/v4.5.0.

**Closed by lakulish** 2023-12-18 17:31 UTC
